# version: "3"

# services:
#   db:
#     build: 
#       context: .
#       dockerfile: Dockerfile.db
#     environment:
#       - POSTGRES_PASSWORD=test
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=engine
#     ports:
#       - 5432:5432
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/etapDB
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etapDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
